### PR TITLE
Add condrestart target in sysvinit and support variables in systemd units

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@dbeer will test this soon (see also #330)

**Comment by stdweird** [comment]
@dbeer tested and verified (please also add to 6.0-dev and 5.1-dev)

**Comment by dbeer** [comment]
Merged into 5.1-dev, 6.0-dev, and develop. (We don't modify master directly.) There were some conflicts when merging into 5.1-dev but I believe I got them sorted out.

**Comment by stdweird** [comment]
@dbeer thanks, but it would be nice if #330 was merged too (now the unitfiles support `PBS_ARGS`, but the rhel sysvinit ones don't)

**Comment by dbeer** [comment]
Done

**Pull request closed without merging**
