### PR TITLE
Support rpm generation with cgroups and the dependency on lssubsys

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@dbeer tested and verified (please also add to 6.0-dev branch)

**Comment by dbeer** [comment]
I merged this into develop and 6.0-dev. Thanks for this patch.

**Comment by mej** [comment]
Just a word of caution:  RPM reserves macros starting with `_` for its own namespace, so user-created macros (unless they re-implement or refine existing upstream macros) should **never** start with `_`.  I would recommend simply `%{rootbin}` instead.

**Comment by stdweird** [comment]
@mej didn't know that. https://github.com/adaptivecomputing/torque/pull/336

**Pull request closed without merging**
