### PR TITLE
Update and extend Travis tests

### PR DESCRIPTION
**Pull request by wpoely86**
These tests are currently failing:
- In `src/test/machine`:
```
Running suite(s): machine test suite methods
80%: Checks: 10, Failures: 2, Errors: 0
test_uut.c:107:F:test_place_and_free_job:test_spread_place:0: called 0
test_uut.c:82:F:test_place_and_free_job:test_place_all_execution_slots:0: Assertion 'placed_all == 2' failed
```
- In `src/test/req_register`:
```
Running suite(s): req_register_suite methods
96%: Checks: 28, Failures: 1, Errors: 0
test_uut.c:686:F:depend_clrrdy_test:set_depend_hold_test:0: Assertion '(pjob2.ji_wattr[JOB_ATR_hold].at_flags & ATR_VFLAG_SET) == 0' failed
```

### CODE REVIEW

**Comment by wpoely86** [comment]
For reference: https://travis-ci.org/wpoely86/torque/builds/161958342

**Comment by dbeer** [comment]
I'm surprised you get tests failing - I just retried and they are passing; we also have a local jenkins server running CI (including the unit tests) and it is green. I suppose you could post the test-suite.log files from those directories to see if they contain any more information about why you're getting a failure.

The pull request looks fine though.

**Comment by wpoely86** [comment]
@dbeer The second failure (`src/test/req_register`) is gone after switching to a newer version of the check tool. However the first one happens both on travis and our own build machine.
The `test-suite.log` shows:
```
Running suite machine test suite methods
test_uut.c:239:P:test_get_hardware_style:test_get_hardware_style:0: Passed
test_uut.c:291:P:test_initializeMachine:test_initializeMachine:0: Passed
test_uut.c:155:P:test_initializeMachine:test_displayAsString:0: Passed
test_uut.c:197:P:test_initializeMachine:test_json_constructor:0: Passed
test_uut.c:173:P:test_initializeMachine:test_basic_constructor:0: Passed
test_uut.c:62:P:test_initializeMachine:test_check_if_possible:0: Passed
test_uut.c:364:P:test_place_and_free_job:test_place_and_free_job:0: Passed
test_uut.c:219:P:test_place_and_free_job:test_store_pci_device_on_appropriate_chip:0: Passed
test_uut.c:107:F:test_place_and_free_job:test_spread_place:0: called 0
test_uut.c:82:F:test_place_and_free_job:test_place_all_execution_slots:0: Assertion 'placed_all == 2' failed
Results for all suites run:
80%: Checks: 10, Failures: 2, Errors: 0
```

Does that help in any way?

**Comment by wpoely86** [comment]
`src/test/req_register` keeps on failing too:
```
Running suite req_register_suite methods
test_uut.c:131:P:check_dependency_job_test:check_dependency_job_test:0: Passed
test_uut.c:161:P:check_dependency_job_test:find_depend_test:0: Passed
test_uut.c:189:P:check_dependency_job_test:clear_depend_test:0: Passed
test_uut.c:209:P:check_dependency_job_test:make_depend_test:0: Passed
test_uut.c:268:P:check_dependency_job_test:register_sync_test:0: Passed
test_uut.c:232:P:check_dependency_job_test:find_dependjob_test:0: Passed
test_uut.c:252:P:check_dependency_job_test:make_dependjob_test:0: Passed
test_uut.c:290:P:register_dep_test:register_dep_test:0: Passed
test_uut.c:315:P:register_dep_test:unregister_dep_test:0: Passed
test_uut.c:323:P:register_dep_test:comp_depend_test:0: Passed
test_uut.c:342:P:register_dep_test:free_depend_test:0: Passed
test_uut.c:373:P:register_dep_test:build_depend_test:0: Passed
test_uut.c:390:P:register_dep_test:dup_depend_test:0: Passed
test_uut.c:508:P:set_depend_test:set_depend_test:0: Passed
test_uut.c:486:P:set_depend_test:encode_depend_test:0: Passed
test_uut.c:464:P:set_depend_test:decode_depend_test:0: Passed
test_uut.c:535:P:depend_clrrdy_test:depend_clrrdy_test:0: Passed
test_uut.c:579:P:depend_clrrdy_test:register_before_dep_test:0: Passed
test_uut.c:605:P:depend_clrrdy_test:register_dependency_test:0: Passed
test_uut.c:631:P:depend_clrrdy_test:release_before_dependency_test:0: Passed
test_uut.c:654:P:depend_clrrdy_test:release_syncwith_dependency_test:0: Passed
test_uut.c:686:F:depend_clrrdy_test:set_depend_hold_test:0: Assertion '(pjob2.ji_wattr[JOB_ATR_hold].at_flags & ATR_VFLAG_SET) == 0' failed
test_uut.c:720:P:depend_clrrdy_test:delete_dependency_job_test:0: Passed
test_uut.c:779:P:depend_clrrdy_test:remove_after_any_test:0: Passed
test_uut.c:450:P:depend_clrrdy_test:req_register_test:0: Passed
test_uut.c:103:P:depend_clrrdy_test:set_array_depend_holds_test:0: Passed
test_uut.c:88:P:depend_clrrdy_test:remove_array_dependency_from_job_test:0: Passed
test_uut.c:71:P:depend_clrrdy_test:test_job_ids_match:0: Passed
Results for all suites run:
96%: Checks: 28, Failures: 1, Errors: 0
```

Full log on https://s3.amazonaws.com/archive.travis-ci.org/jobs/162165329/log.txt (Using GCC 4.8). The output of all `test-suite.log` is at the bottom.

**Comment by dbeer** [comment]
I don't know if you're still following this, but I've worked through these now. I have one remaining failure which has to do with passing Makefile variables correctly through to the unit test.

**Pull request merged**
