### PR TITLE
Enable silent compilation option

### PR DESCRIPTION
**Pull request by HappyCerberus**
This patch enables silent compilation option.

When configured using `configure --enable-silent-rules` the compilation will switch to silent mode producing much more readable output that makes compilation warnings and errors much more noticeable.

More information here: https://autotools.io/automake/silent.html

### CODE REVIEW

**Comment by HappyCerberus** [comment]
I have renamed all .c files in the main compilation pass to .cpp. I haven't converted the schedulers and other auxiliary code (contrib).

**Comment by dbeer** [comment]
Why are you renaming all of the .c files to .cpp? Why not just the class files?

**Comment by HappyCerberus** [comment]
Well, I must admit that I haven't gone that deeply into the build system, but I haven't noticed any of the files being compiled by a C compiler. Everything is compiled with a C++ compiler. So, if that's the case, they should all (naturally) be `.cpp`.

Our fork of the 2.4 version actually combines C and C++ files, but they each get compiled with the respective compiler. So that's also a perfectly viable approach. You need to use `extern C` in the headers/includes in some cases, so it's definitely not as clean.

The main problem with the current state of the repository is that there are files that need to be processed as C++, named `.c`.

**Comment by HappyCerberus** [comment]
In general if the idea is to move fully to C++, then keeping `.c` files is just pointless. Everything compiles as C++ anyway, so keeping `.c` files would just complicate the situation.

**Comment by dbeer** [comment]
I would prefer to change files from .c to .cpp when and if they actually become C++. For now, I like having the files that are pretty much pure C code stay as .c. Does this cause a problem for your IDE?

**Comment by HappyCerberus** [comment]
Well, that depends on what you call a C++ file. As I said, our fork of the 2.4 version mixes C and C++, but they are distinctly compiled with the respective compiler. If you have code that is not valid C code (needs to be compiled with a C++ compiler) in a `.c` file then this will cause issues with all the tools, not just the IDE. `.c` means C code, `.cpp` means C++, that's a really old convention followed by everyone everywhere.

**Pull request closed without merging**
