### PR TITLE
Add RPM build support for '--with-xauth' parameter

### PR DESCRIPTION
**Pull request by jovandeginste**
Can anyone verify if this is the right way to do this? It works, but maybe it's not the canonical way...

### CODE REVIEW

**Comment by mej** [comment]
All the `%ac_with_*` macros correspond to `%bcond_with` or `%bcond_without` definitions from the prior sections, so something like this is not suited for a `%ac_with_*` macro definition.  It would be cleaner to simply place the body of that macro into the configure line, e.g.:

``` rpm
    --with-trqauthd-sock-dir=%{ac_trqauthd_sock_dir} %{?xauth_path:--with-xauth=%{xauth_path}} \
```

**Comment by jovandeginste** [comment]
Like this then?

**Comment by mej** [comment]
LGTM, except for one thing:  I've experienced problems with RPM macros expanded in the `./configure` line where lines with only macros, if all those macros expanded to the empty string (thereby leaving a blank line), would cause problems in the shell.  I've made it a practice therefore to always put macros after non-macro content.

Thus, I would strongly recommend moving what is now line 206 to the end of line 205 as I showed above.  Apart from that one change, I think it's good to be merged AFAICT.

**Comment by dbeer** [comment]
What's the status of this request? It seems like there's a little more work to be done?

**Comment by jovandeginste** [comment]
Sorry, this got lost somewhere in my todo-list

I changed it now, good like that I think?

**Comment by mej** [comment]
Looks good now.

**Comment by dbeer** [comment]
Ok, I merged that, although usually we'd put that in develop. Since this is for the spec file and not a code change, I'm not going to revert. Does this need to be backported to 6.0-dev?

**Comment by mej** [comment]
I'm not sure what your development/branching methodology entails, but if there are to be future releases from `6.0-dev`, I think this change should be stable/inconsequential enough to drop into the "stable" release stream.

**Pull request merged**
