### PR TITLE
Avoid killing running jobs due to time drift when the mom restarts 

### PR DESCRIPTION
**Pull request by itkovian**
This is a workaround for #324.

A real fix would be to avoid the reliance on btime, instead tracking jiffies.

- added logging to track found time differences
- allow for a time difference up to 1 hour (3600 seconds).
- make sure qstat does something when run without arguments (see #322)

### CODE REVIEW

**Comment by itkovian** [comment]
And my editor also kindly removed training whitespace.

**Comment by dbeer** [comment]
Thanks for this change. Normally I'd prefer to have the improvement piece (adding an event class for moms) in a separate pull request so we can look at it separately. 

Thanks for getting a solution in quickly though.

**Comment by dbeer** [comment]
This has also been cherry-picked to develop.

**Comment by itkovian** [comment]
Well, you could have waited and I would have split them ;)

**Comment by dbeer** [comment]
Thanks for that - we'll do that next time.

**Pull request merged**
