### PR TITLE
Add zlib support to tracejob

### LINKED ISSUE #354: Support for handling (g)zipped log files by tracejob
Currently, trace job does not consider log files that have been (g)zipped. The reason for the zipping is pretty straightforward: it saves a huge amount of space. The downside is that trace job does not consider them when looking up information about a job.

Would it be possible to use e.g., zlib to transparently handle files that have been compressed?

### PR DESCRIPTION
**Pull request by wpoely86**
tracejob can now read both plain text and gzip compressed files. zlib has the nice feature that it can read both plain text and gzip compressed files. So all you go to do, is use the zlib io functions.

This fixes #354.

### CODE REVIEW

**Comment by wpoely86** [comment]
I've added a couple of unit tests to show that it works. To do that, I needed to get rid of the global variables in tracejob.

@dbeer what level of C++ do you accept? I guess you're not at C++11/14 yet? Also, `tracejob` is C code but built with a C++ compiler? It can be written more elegant in pure C++(11)?

**Comment by dbeer** [comment]
We support centos/rhel/similar 6 and sles 11, so we have to be able to compile with the compiler that ships on those systems. I believe that is g++ 4.4.7; unfortunately, that doesn't permit using C++11 or 14 at this time.

**Comment by dbeer** [comment]
As far as this change it looks good; the only consideration is whether or not we should add the dependency on this new library by default or through a compile option. I see this as a fairly obvious feature that people will want, but we have some community members that are very picky about adding new build dependencies.

**Comment by wpoely86** [comment]
@dbeer It's not really a 'new' dependency. For all RHEL flavour I know, libxml2 already links with zlib. I don't know about SLES but I guess it's the same there. So currently, `tracejob` is already linked to zlib in a lot of cases.

But it's trivial to put support behind a `#ifdef HAVE_ZLIB`.

**Comment by dbeer** [comment]
That's a good point. Let me test it, and perhaps we'll just merge as is.

**Comment by wpoely86** [comment]
@dbeer Did you find time to have a look? Should I put the changes behind a configure flag or is it good to go?

**Comment by dbeer** [comment]
I finally got to this. Sorry, I got pulled into something.

**Comment by wpoely86** [comment]
Can this also be cherry picked to 6.0-dev (and/or 6.1rc)?

**Comment by dbeer** [comment]
For now I've cherry-picked it into 6.1-dev, to be released with 6.1.0. As long as that gets off without a hitch, we can add this to 6.0-dev (6.0.3).

**Pull request merged**
